apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: dev
  namespace: prod
  namespace: test
  labels: 
    name: redis
    type: backend
spec: 
  containers:
  -  name: redis-container
     image: redis
