apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels: 
    name: redis
    type: backend
    namespace: dev
    namespace: prod
    namespace: test

spec: 
  containers:
  -  name: redis-container
     image: redis
