apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-backend
  labels:
    name: redis
    type: backend
spec:
  template:
    metadata:
      name: redis
      labels:
        name: redis
        type: backend
    spec:
      containers:
      -  name: redis-container
         image: redis
  replicas: 4
  selector:
    matchLabels:
      name: redis
      type: backend
